// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsGuides = {
  guidesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsGuides;
